version: '3.6'
services:
#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    restart: always
#    networks:
#      - done4fun
  api:
    build:
      context: ./backend/
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    restart: always
    networks:
      - done4fun
  postgres:
    image: postgres:14
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - ./docker/postgres/.env
    ports:
      - "5433:5432"
    restart: always
    networks:
      - done4fun
networks:
  done4fun:
    driver: bridge
